[project]
name = "pierre"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marimo>=0.14.11",
    "matplotlib>=3.10.3",
    "polars>=1.31.0",
    "requests>=2.32.4",
]
